name: NavalKingdoms
version: 1.2.1
depend: [WorldGuard, WorldEdit]
author: DF1229

commands:
  nk:
    description: Manage your regions
    usage: Syntax error! /nk <claim|unclaim|reload>
    permission: navalkingdoms.use

permissions:
  navalkingdoms.*:
    description: Allows all commands
    default: OP
    children:
      navalkingdoms.use: true
      navalkingdoms.reload: true
  navalkingdoms.use:
    description: Allows access to the /nk command
  navalkingdoms.reload:
    description: Lets the user reload the plugin

main: me.df1229.plugins.navalkingdoms.NavalKingdoms