name: NavalKingdoms
version: 1.0.0
depend: [WorldGuard, WorldEdit]
author: DF1229

commands:
  nk:
    description: Manage your regions
    usage: Syntax error! /nk <claim|unclaim>
    permission: navalkingdoms.use

permissions:
  navalkingdoms.*:
    description: Allows all commands
    default: OP
    children:
      navalkingdoms.use: true
  navalkingdoms.use:
    description: Allows access to the /nk command

main: me.df1229.plugins.navalkingdoms.NavalKingdoms