name: NavalKingdoms
version: 0.9.7
depend: [WorldGuard, WorldEdit]
author: DF1229

commands:
  nk:
    description: Manage your regions
    usage: Syntax error! /nk <claim|unclaim>
    permission: navalkingdoms.use

permissions:
  navalkingdoms.*:
    description: Allows all commands
    default: OP
    children:
      navalkingdoms.region.claim: true
      navalkingdoms.region.unclaim: true
  navalkingdoms.use:
    description: Allows access to the /nk command
  navalkingdoms.region.*:
    description: Allow all region-related commands
    children:
      navalkingdoms.region.claim: true
      navalkingdoms.region.unclaim: true
  navalkingdoms.region.claim:
    description: Gives access to the /nk claim command
      children:
        navalkingdoms.use: true
  navalkingdoms.region.unclaim:
    description: Gives access to the /nk unclaim command
    children:
      navalkingdoms.use: true

main: me.df1229.plugins.navalkingdoms.NavalKingdoms